use serde::Deserialize;
use serde_xml_rs::from_str;

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
#[serde(rename_all = "PascalCase")]
struct OaiPmh {
    #[serde(rename = "ListRecords")]
    list_records: Option<ListRecords>,
    #[serde(rename = "error")]
    error: Option<OaiError>,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct ListRecords {
    #[serde(rename = "record", default)]
    records: Vec<Record>,
    #[serde(rename = "resumptionToken")]
    resumption_token: Option<String>,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct Record {
    header: RecordHeader,
    metadata: Option<Metadata>,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct RecordHeader {
    identifier: String,
    #[serde(rename = "datestamp")]
    date_stamp: String,
    #[serde(rename = "setSpec", default)]
    set_spec: Vec<String>,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct Metadata {
    #[serde(rename = "dc")]
    dc: DublinCore,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct DublinCore {
    #[serde(rename = "contributor")]
    contributor: Option<String>,
    #[serde(rename = "creator")]
    creator: Option<String>,
    #[serde(rename = "date")]
    date: Option<String>,
    #[serde(rename = "identifier")]
    identifier: Option<String>,
    #[serde(rename = "language")]
    language: Option<String>,
    #[serde(rename = "publisher")]
    publisher: Option<String>,
    #[serde(rename = "relation")]
    relation: Option<String>,
    #[serde(rename = "rights")]
    rights: Option<String>,
    #[serde(rename = "source")]
    source: Option<String>,
    #[serde(rename = "subject")]
    subject: Option<String>,
    #[serde(rename = "title")]
    title: Option<String>,
    #[serde(rename = "type")]
    doc_type: Option<String>,
}

#[allow(dead_code)]
#[derive(Debug, Deserialize)]
struct OaiError {
    #[serde(rename = "@code")]
    code: String,
    #[serde(rename = "$text")]
    message: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_xml_parsing() {
        let xml_data = r#"<?xml version="1.0" encoding="utf-8"?>
            <OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
                <responseDate>2025-10-27T15:23:07Z</responseDate>
                <request from="2024-01-01T00:00:00Z" metadataPrefix="oai_dc" until="2024-01-02T10:09:00Z" verb="ListRecords">https://oai.zbmath.org/v1/</request>
                <ListRecords>
                <record>
                    <header>
                    <identifier>oai:zbmath.org:7781923</identifier>
                    <datestamp>2024-01-02T09:08:40Z</datestamp>
                    <setSpec>81</setSpec>
                    <setSpec>82</setSpec>
                    </header>
                    <metadata>
                    <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                        <dc:contributor>None</dc:contributor>
                        <dc:creator>Basu, Saurabh</dc:creator>
                        <dc:date>2023</dc:date>
                        <dc:identifier>7781923</dc:identifier>
                        <dc:language>English</dc:language>
                        <dc:publisher>None</dc:publisher>
                        <dc:relation>https://zbmath.org/07781923</dc:relation>
                        <dc:rights>Content generated by zbMATH Open, such as reviews,
                classifications, software, or author disambiguation data,
                are distributed under CC-BY-SA 4.0. This defines the license for the
                whole dataset, which also contains non-copyrighted bibliographic
                metadata and reference data derived from I4OC (CC0). Note that the API
                only provides a subset of the data in the zbMATH Open Web interface. In
                several cases, third-party information, such as abstracts, cannot be
                made available under a suitable license through the API. In those cases,
                we replaced the data with the string 'zbMATH Open Web Interface contents
                unavailable due to conflicting licenses.' </dc:rights>
                        <dc:source>Singapore: Springer (ISBN 978-981-9953-20-2/hbk; 978-981-9953-23-3/pbk; 978-981-9953-21-9/ebook). xix, 217~p. (2023).</dc:source>
                        <dc:subject>82-01; 81V70; 82B26; 82B10</dc:subject>
                        <dc:title>Topological phases in condensed matter physics</dc:title>
                        <dc:type>b</dc:type>
                    </oai_dc:dc>
                    </metadata>
                </record>
                <record>
                    <header>
                    <identifier>oai:zbmath.org:7781924</identifier>
                    <datestamp>2024-01-02T09:08:40Z</datestamp>
                    <setSpec>70</setSpec>
                    <setSpec>83</setSpec>
                    </header>
                    <metadata>
                    <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                        <dc:contributor>None</dc:contributor>
                        <dc:creator>Delhom, Adrià; Cano, Alejandro Jiménez; Torralba, Francisco José Maldonado</dc:creator>
                        <dc:date>2023</dc:date>
                        <dc:identifier>7781924</dc:identifier>
                        <dc:language>English</dc:language>
                        <dc:publisher>Springer, Cham</dc:publisher>
                        <dc:relation>https://zbmath.org/07781924</dc:relation>
                        <dc:rights>Content generated by zbMATH Open, such as reviews,
                classifications, software, or author disambiguation data,
                are distributed under CC-BY-SA 4.0. This defines the license for the
                whole dataset, which also contains non-copyrighted bibliographic
                metadata and reference data derived from I4OC (CC0). Note that the API
                only provides a subset of the data in the zbMATH Open Web interface. In
                several cases, third-party information, such as abstracts, cannot be
                made available under a suitable license through the API. In those cases,
                we replaced the data with the string 'zbMATH Open Web Interface contents
                unavailable due to conflicting licenses.' </dc:rights>
                        <dc:source>SpringerBriefs in Physics. Cham: Springer (ISBN 978-3-031-40432-0/pbk; 978-3-031-40433-7/ebook). xi, 71~p. (2023).</dc:source>
                        <dc:subject>70-02; 70Sxx; 83Dxx</dc:subject>
                        <dc:title>Instabilities in field theory. A primer with applications in modified gravity</dc:title>
                        <dc:type>b</dc:type>
                    </oai_dc:dc>
                    </metadata>
                </record>
                <record>
                    <header>
                    <identifier>oai:zbmath.org:7781926</identifier>
                    <datestamp>2024-01-02T09:08:40Z</datestamp>
                    <setSpec>37</setSpec>
                    <setSpec>68</setSpec>
                    </header>
                    <metadata>
                    <oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                        <dc:contributor>Thomas B. Ward (Durham)</dc:contributor>
                        <dc:creator>Fukś, Henryk</dc:creator>
                        <dc:date>2023</dc:date>
                        <dc:identifier>7781926</dc:identifier>
                        <dc:language>English</dc:language>
                        <dc:publisher>Springer, Cham</dc:publisher>
                        <dc:relation>https://zbmath.org/07781926</dc:relation>
                        <dc:rights>Content generated by zbMATH Open, such as reviews,
                classifications, software, or author disambiguation data,
                are distributed under CC-BY-SA 4.0. This defines the license for the
                whole dataset, which also contains non-copyrighted bibliographic
                metadata and reference data derived from I4OC (CC0). Note that the API
                only provides a subset of the data in the zbMATH Open Web interface. In
                several cases, third-party information, such as abstracts, cannot be
                made available under a suitable license through the API. In those cases,
                we replaced the data with the string 'zbMATH Open Web Interface contents
                unavailable due to conflicting licenses.' </dc:rights>
                        <dc:source>Understanding Complex Systems; Springer: Complexity. Cham: Springer (ISBN 978-3-031-38699-2/hbk; 978-3-031-38702-9/pbk; 978-3-031-38700-5/ebook). xix, 296~p. (2023).</dc:source>
                        <dc:subject>37-02; 37B15; 37B10; 68Q80</dc:subject>
                        <dc:title>Solvable cellular automata. Methods and applications</dc:title>
                        <dc:type>b</dc:type>
                    </oai_dc:dc>
                    </metadata>
                </record>
                </ListRecords>
            </OAI-PMH>
        "#;

        let data: OaiPmh = from_str(xml_data).expect("Failed to deserialize XML");
        println!("{:?}", data);
    }
}
